apiVersion: apps/v1
kind: Deployment
metadata:
  name: autovyn-frontend
  namespace: dev
  labels:
    app: autovyn-frontend
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: autovyn-frontend
  template:
    metadata:
      labels:
        app: autovyn-frontend
        env: dev
    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        fsGroup: 1000
      containers:
      - name: frontend
        image: us-central1-docker.pkg.dev/gcp-assignment-471905/gcp-assignment-repo/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
