apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: dev
type: Opaque
data:
  password: VGVyYWJoYWlzaWRoZW1hdXRfMw==  # base64 encoded "Terabhaisidhemaut_3"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: autovyn-app-sa
  namespace: dev
  annotations:
    iam.gke.io/gcp-service-account: autovyn-app@${GOOGLE_CLOUD_PROJECT}.iam.gserviceaccount.com
