apiVersion: apps/v1
kind: Deployment
metadata:
  name: autovyn-worker
  namespace: dev
  labels:
    app: autovyn-worker
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autovyn-worker
  template:
    metadata:
      labels:
        app: autovyn-worker
        env: dev
    spec:
      containers:
      - name: worker
        image: us-central1-docker.pkg.dev/gcp-assignment-471905/gcp-assignment-repo/worker:latest
        ports:
        - containerPort: 9091
        env:
        - name: DB_HOST
          value: "10.75.192.3"  # Cloud SQL private IP
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "postgres"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: GCS_BUCKET
          value: "gcp-assignment-uploads-471905"
        - name: PUBSUB_TOPIC
          value: "gcp-assignment-topic"
        - name: GOOGLE_CLOUD_PROJECT
          value: "gcp-assignment-471905"
        - name: GOOGLE_CLOUD_REGION
          value: "us-central1"
        livenessProbe:
          httpGet:
            path: /health
            port: 9091
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 9091
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
