server:
  port: 9090
management:
  endpoints:
    web:
      exposure:
        include: info,health
  endpoint:
    health:
      show-details: always

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:autovyn_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      repositories:
        enabled: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

app:
  uploadDir: uploads
  gcs:
    bucket: ${GCS_BUCKET:gcp-assignment-uploads-471905}
  pubsub:
    topic: ${PUBSUB_TOPIC:gcp-assignment-topic}
  worker:
    url: ${WORKER_URL:http://localhost:9091}

gcp:
  project-id: ${GOOGLE_CLOUD_PROJECT:gcp-assignment-471905}
  region: ${GOOGLE_CLOUD_REGION:us-central1}

